---
downloads: ~/.ansible-downloads/

configure_sudoers: yes
configure_osx:     yes

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - autojump
  - awscli
  - composer
  - doctl
  - git
  - hub
  - jq
  - kubectl
  - libevent
  - sqlite
  - mcrypt
  - neovim
  - node
  - php
  - openssl
  - pass
  - reattach-to-user-namespace
  - terraform
  - tor
  - tmux
  - wget
  - yarn
  - zsh
homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-versions
homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - alfred
  - amazon-music
  - aws-vault
  - brave-browser
  - chromedriver
  - dash2
  - docker
  - dropbox
  - firefox
  - google-chrome
  - google-drive-file-stream
  - iterm2
  - libreoffice
  - nextcloud
  - nvalt
  - phpstorm
  - sequel-pro
  - skitch
  - slack
  - tor-browser
  - vagrant
  - virtualbox
  - vnc-viewer

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 557168941, name: "Tweetbot" }
mas_email: "toby@cubicmushroom.co.uk"
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages:
  - name: hirak/prestissimo
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A
  # - powerline-status

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
