---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ items }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mas
      tags: ['mas']

  tasks:
    - include_tasks: tasks/ansible-setup.yml

    - include_tasks: tasks/sudoers.yml
      when:          configure_sudoers
